application:
  name: httpbin
  project: basicWwwAppAwsDeploysvPe0Ucm
  publicly_accessible: true
  organization: QoveryTest
routers:
  - name: main
    routes:
      - application_name: httpbin
        paths:
          - /*
